apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kalshi-tradr

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - bot.yaml

commonLabels:
  app.kubernetes.io/part-of: kalshi-tradr
